### ISSUE TITLE
uirouter版本问题

### ISSUE THREAD

**Issue by morance** [easyops-cn/generator-console-package#15]
uirouter 需要固定版本跟主站一致，不能直接安装最新版本，不然component注入会报错。
当前主站：@uirouter/angular@2.0.0 @uirouter/core@5.0.19

**Comment by JLHwung** [comment]
Please elaborate your issue by answering the following question:

How can this be reproduced?

What is the expected behaviour?

What is the actual behaviour?

**Comment by morance** [comment]
How can this be reproduced?
直接使用generator生成component，组件内注入uirouter的transition即可复现问题。

What is the expected behaviour?
不报错，直接能使用注入提供的东西。

What is the actual behaviour?
直接报错
![image](https://user-images.githubusercontent.com/24826592/49134963-4f50d280-f320-11e8-962e-e62f21a4de33.png)

**Comment by weareoutman** [comment]
@morance 哪个 scope 下的？
