### ISSUE TITLE
module name is better prefix with scope name

### ISSUE THREAD

**Issue by liangsz** [easyops-cn/generator-console-package#27]
![image](https://user-images.githubusercontent.com/1570124/49360833-4cd1ec80-f715-11e8-8296-70dac4e9da06.png)

**Comment by JLHwung** [comment]
> how about only prefix when scope is brick?

I don't quite understand. We never need import a `brick` module because plugin manager will handle the mounting step.

> PluginCommonXyzModule or ConsolePluginAbcModule is too long to type.

You can use shorter initial letter abbreviations:

`PCFooModule` or `CPBarModule`.

**Comment by weareoutman** [comment]
> We never need import a brick module because plugin manager will handle the mounting step.

Cause the template is shared with scope=@easyops and scope=@plugin-common which have exported modules. And globally unique module names help IDE auto completion.
